#!/bin/sh
#  gitR2 Launcher (Prod Version)

        FRT_Scr=FRT42_gitR2_p1.02.sh                                  # .(41210.02.6)

#       FRT_Dir=$( realpath "$0" ); FRT_Dir=$( dirname "${FRT_Dir}" ) ##.(41210.02.6)
        FRT_Dir="$( cd "$( dirname "$0" )" && pwd )"                  # .(41210.02.6)

#echo "$FRT_Dir/$FRT_Scr" "$@"; exit
      "$FRT_Dir/$FRT_Scr" "$@"                                        # .(41210.02.6)

