#!/bin/sh
#   RSS Info (Prod Copy)

#       RSS_Scr=RSS22-Info_v0.7.80923.sh
#       RSS_Scr=RSS22-Info_p0.08.81014.sh
#       RSS_Scr=RSS22_Info_p0.08.sh
        RSS_Scr=RSS23_Info_p0.09.sh                                   # .(41210.02.13) 

#       RSS_Dir=$( realpath "$0" ); RSS_Dir=$( dirname "${JPT_Dir}" ) ##.(41210.02.13)
        RSS_Dir="$( cd "$( dirname "$0" )" && pwd )"                  # .(41210.02.13)

      "$RSS_Dir/$RSS_Scr" "$@"                                        # .(41210.02.13) 
